### PR TITLE
Microverse Project #3 Positioning and Floating Elements

### PR DESCRIPTION
**Pull request by KennyUTN**
Worked alone on this project with the authorization of Greg Barret.

I know the project is not in a perfect state and that some things could improve. But in order for me to catch up with my stand up team I would like a quick review so I can start with project #4!

### CODE REVIEW

**Comment by mikenath223** [comment]
### Pull request currently under review by Michgolden Ukeje (TSE).
Kindly exercise patience 👋

**Review by mikenath223 — CHANGES_REQUESTED** [review]
### Hi @KennyUTN  👋

You've done quite well on this project.👍

You are moments away from a thumbs-up kindly make the following changes:

- [ ] Fix the linting errors on your CSS file, we need this mark(❌) beside your commit to turn to this mark(✅).

 - [ ] In addition, kindly amend this section in the screenshot below. Please make sure that in each of the smaller sections containing images, ensure that the images are properly aligned directly above their corresponding text, the images look quite out of place in yours.[Screenshots]👇

THIS IS YOURS  |  THIS IS WHAT IS EXPECTED
---------------  |  --------------
ice_screenshot_20200504-145926  |  ice_screenshot_20200504-150009
. | .

 - [ ] Also kindly take note of the look of the section that comes above the footer, notice that there it looks different than what appears on yours, kindly make the necessary changes.
[Screenshot]👇

THIS IS YOURS  |  THIS IS WHAT IS EXPECTED
---------------  |  --------------
 ice_screenshot_20200504-145752  |  ice_screenshot_20200504-145733
 . | .

Kindly fix these issues and request another review👍
Feel free to contact me on slack(michgolden) if you need further clarification.

HAPPY CODING👨‍💻

**Comment by KennyUTN** [comment]
Hi Mich what's up

After writing this I'll fix the linting problems, regarding the other 2 things

> * [ ]  In addition, kindly amend this section in the screenshot below. Please make sure that in each of the smaller sections containing images, ensure that the images are properly aligned directly above their corresponding text, the images look quite out of place in yours.[Screenshots]👇


This is a problem because we are working on different resolutions, the section with images looks perfect on my screen. Keep in mind **responsiveness is not a requirement for this project.**

githubScreen1


>Also kindly take note of the look of the section that comes above the footer, notice that there it looks different than what appears on yours, kindly make the necessary changes.

Regarding this part, it is because you are not opening the nytimes webpage on an "INCOGNITO WEB BROWSER", as the odin project page tells you to do, so it will obviously look different.
When you open it on incognito mode, it looks identical to the one I made.

Screenshot from [https://www.nytimes.com/2014/03/18/science/space/detection-of-waves-in-space-buttresses-landmark-theory-of-big-bang.html?_r=0](url). When you open it on Incognito mode. Please see that it looks the same as the one on my project.

GithubScreen2

**Comment by mikenath223** [comment]
> Hi Mich what's up
> 
> After writing this I'll fix the linting problems, regarding the other 2 things
> 
> > * [ ]   In addition, kindly amend this section in the screenshot below. Please make sure that in each of the smaller sections containing images, ensure that the images are properly aligned directly above their corresponding text, the images look quite out of place in yours.[Screenshots]👇
> 
> This is a problem because we are working on different resolutions, the section with images looks perfect on my screen. Keep in mind **responsiveness is not a requirement for this project.**
> 
> githubScreen1
> 
> > Also kindly take note of the look of the section that comes above the footer, notice that there it looks different than what appears on yours, kindly make the necessary changes.
> 
> Regarding this part, it is because you are not opening the nytimes webpage on an "INCOGNITO WEB BROWSER", as the odin project page tells you to do, so it will obviously look different.
> When you open it on incognito mode, it looks identical to the one I made.
> 
> Screenshot from [https://www.nytimes.com/2014/03/18/science/space/detection-of-waves-in-space-buttresses-landmark-theory-of-big-bang.html?_r=0](url). When you open it on Incognito mode. Please see that it looks the same as the one on my project.
> 
> GithubScreen2

However kindly note that according to the Odin instructions you were asked to view the page on incognito mode if you have passed your monthly limit, let me know if that is the case in for you.
In addition according to the Odin requirements also you were required that to view The Theory of Inflation section you would need to widen your viewing window for it to show up properly.

**Comment by mikenath223** [comment]
### Hi again @KennyUTN 👋

I apologize that this wasn't stated in the previous review.

Please add a live link to your own project in the readme file.

Keep going.🚀

**Review by christianotieno — CHANGES_REQUESTED** [review]
# **CHANGES REQUIRED** :warning:
Hey @KennyUTN  :wave:
-
You have done a splendid job! :tada: I love how clean and modular your code is. Keep it up.
We, however, do have some few changes to carry out before we proceed (see review comment).
##
- The project looks great we should, however, make sure that nothing is messed up with this one.
##
## [RECOMMENDATION]:
- Good job with the summary. We can always improve on it next time by highlighting what we have carried out in the project's PR to guide the reviewer on what has been achieved so far. :smile:

## [REQUIRED] - UPDATE your README
- The project is expected to have a descriptive README.md ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/descriptive_readme.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243643/))
- Kindly improve on our README. Let's have a live link to our source page. Use this [template](https://github.com/microverseinc/readme-template) to make it look more professional thank you!

- The navbar is not properly implemented. The links appear widely stretched across the navbar than is seen in the source page. Kindly see the difference below. 

|clone|source page|
|:---:|:---:|
|clone|source|

- I am unable to see the main image.
image

- Lastly, kindly for this project to be approved, the linter checks must all pass the tests. Kindly fix the linter errors.
- If you have any questions, let me know here or on slack and I will be glad to clarify with you. You can also reach me and connect with me on my social media or email. :eyes:
##
- When you have made the specified changes, please submit another code review. Thank you!
Happy coding :smile:
**[Christian Otieno](https://github.com/ChristianOtieno)**
[Twitter](https://twitter.com/iamchrisotieno) [linkedin](https://www.linkedin.com/in/christianotieno/) [GitLab](https://gitlab.com/christianotieno)
---
*P.S. all requested changes not marked by [OPTIONAL] or are not positive comments are **REQUIRED***

**Comment by trekab** [comment]
# Changes Required.
Hello @KennyUTN, this is impressive work given that you are working alone on this project. :clap:
There are a few touches to make to complete though;
- [ ] Fix all the [HTML validator](https://validator.w3.org/#validate_by_upload) errors.([screen shot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/section/validation_requirement.png) from Pathwright)
- [ ] Your navigation bar elements appear to be centered i.e there is too much space to the left and right of the navigation. The "Hamburger button", search icon, and the link with text should be on the leftmost side, the NY Times image logo embedded in the center, and the 'Log in' elements should be on the rightmost side.(Compare with [original](https://www.nytimes.com/2014/03/18/science/space/detection-of-waves-in-space-buttresses-landmark-theory-of-big-bang.html?_r=0))

__Kindly work on the above changes and submit another code review request__
_Feel free to slack me for any inquiries about this review_ :wink: 
__Treasure Kabareebe__

**Review by serdg0 — APPROVED** [review]
Congratulations @KennyUTN ! :100: 
You are free to merge to master.
Keep the good work in your next project!

Happy Coding! :computer: :nerd_face:

**Pull request merged**
